// Generated by Selenium IDE
const {Builder, By, Key, until} = require('selenium-webdriver')
const assert = require('assert')

describe('add_detalies_Saloodo', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit();
    })
    it('add_detalies_Saloodo', async function () {
        await driver.get("https://demo.saloodo.com/")
        await driver.manage().window().setRect({width: 738, height: 680})
        await driver.findElement(By.linkText("Login")).click()
        await driver.findElement(By.css(".sc-euEtCV")).click()
        await driver.findElement(By.css(".sc-euEtCV")).sendKeys("strelnykdanny@gmail.com")
        await driver.findElement(By.css(".sc-fHCHyC")).click()
        await driver.findElement(By.css(".sc-fHCHyC")).click()
        await driver.findElement(By.css(".sc-fHCHyC")).click()
        await driver.findElement(By.css(".sc-fHCHyC")).sendKeys("Svetkin31@")
        {
            const element = await driver.findElement(By.css(".sc-bdnxRM > span"))
            await driver.actions({bridge: true}).moveToElement(element).clickAndHold().perform()
        }
        {
            const element = await driver.findElement(By.css(".sc-bdnxRM"))
            await driver.actions({bridge: true}).moveToElement(element).release().perform()
        }
        await driver.findElement(By.css(".sc-bdnxRM")).click()
        {
            const element = await driver.findElement(By.css(".sc-bdnxRM"))
            await driver.actions({bridge: true}).moveToElement(element).perform()
        }
        {
            const element = await driver.findElement(By.css(".sc-gzVnrw:nth-child(1) > span"))
            await driver.actions({bridge: true}).moveToElement(element).clickAndHold().perform()
        }
        {
            const element = await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)"))
            await driver.actions({bridge: true}).moveToElement(element).release().perform()
        }
        await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)")).click()
        {
            const element = await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)"))
            await driver.actions({bridge: true}).moveToElement(element).perform()
        }
        await driver.findElement(By.css(".jfoOna > .sc-kpOJdX")).click()
        await driver.findElement(By.css(".jfoOna > .sc-kpOJdX")).sendKeys("martin strasse 3")
        await driver.executeScript("window.scrollTo(0,0)")
        await driver.findElement(By.css(".jfoOna > .sc-kpOJdX")).click()
        await driver.findElement(By.css(".jfoOna > .sc-kpOJdX")).sendKeys("bohn")
        await driver.findElement(By.css(".jfoOna > .sc-kpOJdX")).click()
        await driver.findElement(By.css(".jfoOna > .sc-kpOJdX")).sendKeys("234345533")
        await driver.findElement(By.css(".jfoOna > .sc-kpOJdX")).click()
        await driver.findElement(By.css(".jfoOna > .sc-kpOJdX")).sendKeys("GB223462237")
        {
            const element = await driver.findElement(By.css(".sc-gzVnrw:nth-child(1) > span"))
            await driver.actions({bridge: true}).moveToElement(element).perform()
        }
        {
            const element = await driver.findElement(By.CSS_SELECTOR, "body")
            await driver.actions({bridge: true}).moveToElement(element, 0, 0).perform()
        }
        {
            const element = await driver.findElement(By.css(".sc-gzVnrw:nth-child(1) > span"))
            await driver.actions({bridge: true}).moveToElement(element).clickAndHold().perform()
        }
        {
            const element = await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)"))
            await driver.actions({bridge: true}).moveToElement(element).release().perform()
        }
        await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)")).click()
        await driver.executeScript("window.scrollTo(0,0)")
        await driver.findElement(By.css(".dpRPPV > .sc-cmthru")).click()
        await driver.findElement(By.css(".sc-kpOJdX:nth-child(1)")).click()
        await driver.findElement(By.css(".sc-kpOJdX:nth-child(1)")).sendKeys("4")
        await driver.findElement(By.css(".css-yitmv4-control > .css-1ih1euq")).click()
        await driver.findElement(By.id("react-select-8-option-2")).click()
        await driver.findElement(By.css(".sc-gzVnrw:nth-child(1) > span")).click()
        await driver.executeScript("window.scrollTo(0,0)")
        {
            const element = await driver.findElement(By.css(".so360e-1 .sc-dnqmqq"))
            await driver.actions({bridge: true}).moveToElement(element).perform()
        }
        await driver.findElement(By.css(".sc-bHwgHz:nth-child(1) .sc-fjmCvl")).click()
        await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)")).click()
        {
            const element = await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)"))
            await driver.actions({bridge: true}).moveToElement(element).perform()
        }
        {
            const element = await driver.findElement(By.CSS_SELECTOR, "body")
            await driver.actions({bridge: true}).moveToElement(element, 0, 0).perform()
        }
        {
            const element = await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)"))
            await driver.actions({bridge: true}).moveToElement(element).perform()
        }
        {
            const element = await driver.findElement(By.css(".css-1lta616-indicatorContainer > .css-19bqh2r"))
            await driver.actions({bridge: true}).moveToElement(element).clickAndHold().perform()
        }
        {
            const element = await driver.findElement(By.css(".css-1lta616-indicatorContainer path"))
            await driver.actions({bridge: true}).moveToElement(element).release().perform()
        }
        await driver.findElement(By.css(".css-1lta616-indicatorContainer > .css-19bqh2r")).click()
        await driver.findElement(By.css(".css-1c13dor-control > .css-1hwfws3")).click()
        await driver.findElement(By.css(".css-1c13dor-control > .css-1hwfws3")).click()
        await driver.findElement(By.css(".css-1lta616-indicatorContainer > .css-19bqh2r")).click()
        await driver.findElement(By.id("react-select-10-option-1")).click()
        {
            const element = await driver.findElement(By.css(".css-1lta616-indicatorContainer > .css-19bqh2r"))
            await driver.actions({bridge: true}).moveToElement(element).clickAndHold().perform()
        }
        {
            const element = await driver.findElement(By.css(".css-1lta616-indicatorContainer"))
            await driver.actions({bridge: true}).moveToElement(element).release().perform()
        }
        await driver.findElement(By.css(".css-1lta616-indicatorContainer")).click()
        await driver.findElement(By.id("react-select-12-option-0")).click()
        await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)")).click()
        {
            const element = await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)"))
            await driver.actions({bridge: true}).moveToElement(element).perform()
        }
        {
            const element = await driver.findElement(By.CSS_SELECTOR, "body")
            await driver.actions({bridge: true}).moveToElement(element, 0, 0).perform()
        }
        await driver.findElement(By.css(".css-yitmv4-control > .css-1ih1euq")).click()
        await driver.findElement(By.id("react-select-14-option-1")).click()
        await driver.findElement(By.css(".sc-dxgOiQ")).click()
        await driver.findElement(By.css(".sc-dxgOiQ")).sendKeys("test test test")
        {
            const element = await driver.findElement(By.css(".sc-gzVnrw:nth-child(1) > span"))
            await driver.actions({bridge: true}).moveToElement(element).clickAndHold().perform()
        }
        {
            const element = await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)"))
            await driver.actions({bridge: true}).moveToElement(element).release().perform()
        }
        await driver.findElement(By.css(".sc-gzVnrw:nth-child(1)")).click()
        await driver.executeScript("window.scrollTo(0,0)")
        await driver.findElement(By.css(".sc-jnlKLf")).click()
        await driver.findElement(By.css(".sc-hrWEMg:nth-child(2)")).click()
        await driver.findElement(By.css(".sc-gGLxEB")).click()
        await driver.findElement(By.css(".sc-ikXwFM > .sc-uxdHp")).click()
    })
})
