// Generated by Selenium IDE
const {Builder, By, Key, until} = require('selenium-webdriver')
const assert = require('assert')

describe('Login_Saloodo', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit();
    })
    it('Login_Saloodo', async function () {
        await driver.get("https://demo.saloodo.com/")
        await driver.manage().window().setRect({width: 738, height: 680})
        await driver.findElement(By.linkText("Login")).click()
        await driver.findElement(By.css(".sc-euEtCV")).click()
        await driver.findElement(By.css(".sc-euEtCV")).sendKeys("sstrelnyk@gmail.com")
        await driver.findElement(By.css(".sc-fHCHyC")).click()
        await driver.findElement(By.css(".sc-fHCHyC")).click()
        await driver.findElement(By.css(".sc-fHCHyC")).click()
        await driver.findElement(By.css(".sc-fHCHyC")).sendKeys("Svetkin31@")
        {
            const element = await driver.findElement(By.css(".sc-bdnxRM > span"))
            await driver.actions({bridge: true}).moveToElement(element).clickAndHold().perform()
        }
        {
            const element = await driver.findElement(By.css(".sc-bdnxRM"))
            await driver.actions({bridge: true}).moveToElement(element).release().perform()
        }
        await driver.findElement(By.css(".sc-bdnxRM")).click()
        {
            const element = await driver.findElement(By.css(".sc-bdnxRM"))
            await driver.actions({bridge: true}).moveToElement(element).perform()
        }
        await driver.findElement(By.css(".sc-jnlKLf")).click()
        await driver.findElement(By.css(".sc-hrWEMg:nth-child(3)")).click()
    })
})
