// Generated by Selenium IDE
const {Builder, By, Key, until} = require('selenium-webdriver')
const assert = require('assert')

describe('Registration_Saloodo', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit();
    })
    it('Registration_Saloodo', async function () {
        await driver.get("https://demo.saloodo.com/")
        await driver.manage().window().setRect({width: 738, height: 680})
        await driver.findElement(By.linkText("Register")).click()
        await driver.findElement(By.css(".cUtRmq")).click()
        await driver.findElement(By.name("company")).click()
        await driver.findElement(By.name("company")).sendKeys("Transport")
        await driver.findElement(By.name("firstName")).click()
        await driver.findElement(By.name("firstName")).sendKeys("Anna")
        await driver.findElement(By.name("lastName")).click()
        await driver.findElement(By.name("lastName")).sendKeys("Family")
        await driver.findElement(By.name("undefined-number")).click()
        await driver.findElement(By.name("undefined-number")).sendKeys("123 2342233")
        await driver.findElement(By.name("email")).click()
        await driver.findElement(By.name("email")).sendKeys("sstrelnyk@gmail.com")
        await driver.findElement(By.name("password")).click()
        await driver.findElement(By.name("password")).click()
        await driver.findElement(By.name("password")).click()
        await driver.findElement(By.name("password")).sendKeys("Svetikin31@")
        await driver.findElement(By.css(".hOYivT > .sc-biJonm")).click()
        await driver.findElement(By.css(".giWHVN")).click()
        {
            const element = await driver.findElement(By.css(".sc-bdnxRM > span"))
            await driver.actions({bridge: true}).moveToElement(element).clickAndHold().perform()
        }
        {
            const element = await driver.findElement(By.css(".sc-bdnxRM"))
            await driver.actions({bridge: true}).moveToElement(element).release().perform()
        }
        await driver.findElement(By.css(".sc-bdnxRM")).click()
        {
            const element = await driver.findElement(By.css(".sc-bdnxRM"))
            await driver.actions({bridge: true}).moveToElement(element).perform()
        }
        await driver.executeScript("window.scrollTo(0,50)")
        await driver.executeScript("window.scrollTo(0,50)")
        await driver.findElement(By.css("path:nth-child(2)")).click()
        await driver.findElement(By.css(".sc-jeCdPy:nth-child(5) .sc-bEjcJn")).click()
        await driver.findElement(By.css(".sc-hSmEHG:nth-child(6)")).click()
    })
})
